apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/ваш-username/my-gitops-app.git
    path: charts/my-app
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
