apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-redis-chart.fullname" . }}-nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html><body><h1>Hello from Nginx in Kubernetes!</h1><p>Redis value: {{ .Values.redis.value }}</p></body></html>
