apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <!DOCTYPE html>
    <html><body><h1>Hello from Nginx in Kubernetes!</h1><p>Redis value: {{REDIS_VALUE}}</p></body></html>
