apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc  # Динамическое имя
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP  # Или NodePort/LoadBalancer
  ports:
  - port: 80       # Порт сервиса
    targetPort: 80 # Порт пода (должен совпадать с контейнером)
    protocol: TCP
  selector:
    app: {{ .Release.Name }}  # Должен совпадать с labels в Deployment
