name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Kubernetes Cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Get current context
        run: kubectl config current-context

      - name: Show nodes (test connectivity)
        run: kubectl get nodes

#      - name: Apply Kubernetes manifests
#        run: |
#          kubectl apply -f k8s/
