name: Helm CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-helm-chart:
    name: Deploy Helm Chart to Kubernetes
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Write kubeconfig file
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG_CONTENT" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set KUBECONFIG
        run: |
          export KUBECONFIG=~/.kube/config

      - name: Check Kubernetes context
        run: |
          kubectl config current-context

      - name: Helm upgrade --install from OCI
        run: |
          helm upgrade --install my-release oci://registry-1.docker.io/bitnamicharts/nginx --version 19.0.1

      - name: Show service URL
        run: |
          export SERVICE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].port}" services my-release-nginx)
          export SERVICE_IP=$(kubectl get svc --namespace default my-release-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Service URL: http://${SERVICE_IP}:${SERVICE_PORT}"
