name: Helm Chart CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-helm-chart:
    name: Build and Lint Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Run Helm Lint
        run: |
          helm lint ./nginx-redis-chart

      - name: Package Helm Chart
        run: |
          helm package ./nginx-redis-chart --destination ./chart-output

      - name: List packaged chart
        run: |
          ls -la ./chart-output/

      - name: Upload Helm Chart as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: ./chart-output/

  deploy-helm-chart:
    name: Deploy Helm Chart to Kubernetes
    needs: build-helm-chart
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Helm Chart
        uses: actions/download-artifact@v4
        with:
          name: helm-chart
          path: ./chart-output

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Create .kube directory
        run: |
          mkdir -p ~/.kube

      - name: Write kubeconfig file
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
        run: |
          echo "$KUBECONFIG_CONTENT" | base64 -d > ~/.kube/config
	  chmod 600 ~/.kube/config

      - name: Set KUBECONFIG
        run: |
          export KUBECONFIG=~/.kube/config

      - name: Use default context
  	run: |
	  kubectl config use-context orbstack || echo "Context not found"

      - name: Check Kubernetes nodes
        run: |
          kubectl get nodes

      - name: Upgrade or install Helm release
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Helm repo update
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Helm upgrade --install
        run: |
          helm upgrade --install my-release ./chart-output/*.tgz
